run:
  timeout: 5m

issues:
  exclude-dirs:
    - docs
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo

linters-settings:
  govet:
    enable:
      - shadow
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - misspell
