version: 2

run:
  timeout: 5m
  skip-dirs:
    - docs
    - vendor  # если нужно
  # или skip-dirs-use-default: true (включает стандартные: vendor, testdata, examples и т.д.)

linters-settings:
  govet:
    check-shadowing: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
